run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - goconst
    # - gocyclo
    - errcheck
    - misspell
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
